# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c06083703308bb0f27e9e136f1a0665987addf6bea95efd30f5d42eaea38aacff2b5504a93cdd7995f2cd6b2a484f121fc2173a33d68e306b1484c956f90d04e

test:
  secret_key_base: b1eff49127b8ebeeab91e71775e7058ff58a1b9475b09a00f2856cbf0a58c8fa018d8635c72eccd900200df436af9b00580561858b41443bb375560830d35d39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
